services:
  - type: web
    region: ohio
    name: jsbss
    env: docker         # Changed from python to docker
    buildCommand: ""    # Empty build command for docker env
    startCommand: ""    # Empty start command for docker env
    plan: free
    numInstances: 1

    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_APP_KEY
        value: "any key works"
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-jsb
          property: connectionString
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata/

databases:
  - name: postgresql-jsb
    region: ohio
    ipAllowList: []
    plan: free

